### ISSUE TITLE
Service implementation to entity classes

### ISSUE THREAD

**Issue by esfdk** [itu-bswu/RentIt#8]
GetUsers
GetContentPublishers
EditMovieInformation
GetMovieInformation

should be moved to entity classes(where it makes sense) and tests should be rewritten...

**Comment by NiklasHansen** [comment]
I suggest we postpone this to after feature freeze. We have some time between feature freeze and code freeze to do such things.

**Comment by NiklasHansen** [comment]
GetUsers and GetContentPublishers have been removed in V2, as we don't provide any other admin features. So to avoid the maintenance for now, they have been removed. I here refer to the meeting prior to the service interface refactoring (aka V2).

EditMovieInformation and GetMovieInformation have been refactored out into the entity classes.
